export const demoData = [
  {
    name: "Dr Katie Hayes",
    gender: "female",
    group: "Practitioner",
    avatar: "https://randomuser.me/api/portraits/thumb/women/82.jpg",
    email: "katie.hayes@example.com",
    favorite: false,
  },
  {
    name: "Dr. Anna-Sophie Van Hulst",
    gender: "female",
    group: "Practitioner",
    avatar: "https://randomuser.me/api/portraits/thumb/women/27.jpg",
    email: "anna-sophie.vanhulst@example.com",
    favorite: false,
  },
  {
    name: "Dr. Oscar Cooper",
    gender: "male",
    group: "Practitioner",
    avatar: "https://randomuser.me/api/portraits/thumb/men/55.jpg",
    email: "oscar.cooper@example.com",
    favorite: false,
  },
  {
    name: "Dr. Fiona Fleming",
    gender: "female",
    group: "Practitioner",
    avatar: "https://randomuser.me/api/portraits/thumb/women/70.jpg",
    email: "fiona.fleming@example.com",
    favorite: true,
  },
  {
    name: "Ass. Deniz Sadıklar",
    gender: "female",
    group: "Assistant",
    avatar: "https://randomuser.me/api/portraits/thumb/women/68.jpg",
    email: "deniz.sadiklar@example.com",
    favorite: false,
  },
  {
    name: "Ass. Irina Damjanović",
    gender: "female",
    group: "Assistant",
    avatar: "https://randomuser.me/api/portraits/thumb/women/57.jpg",
    email: "irina.damjanovic@example.com",
    favorite: false,
  },
  {
    name: "Ass. Francis Holmes",
    gender: "male",
    group: "Assistant",
    avatar: "https://randomuser.me/api/portraits/thumb/men/25.jpg",
    email: "francis.holmes@example.com",
    favorite: false,
  },
  {
    name: "Ass. Vicenta López",
    gender: "female",
    group: "Assistant",
    avatar: "https://randomuser.me/api/portraits/thumb/women/19.jpg",
    email: "vicenta.lopez@example.com",
    favorite: false,
  },
  {
    name: "Ass. Max Bergli",
    gender: "male",
    group: "Assistant",
    avatar: "https://randomuser.me/api/portraits/thumb/men/11.jpg",
    email: "max.bergli@example.com",
    favorite: false,
  },
  {
    name: "Ass. Milica Da Silva",
    gender: "female",
    group: "Assistant",
    avatar: "https://randomuser.me/api/portraits/thumb/women/18.jpg",
    email: "milica.dasilva@example.com",
    favorite: false,
  },
  {
    name: "Ass. Väinö Honkala",
    gender: "male",
    group: "Assistant",
    avatar: "https://randomuser.me/api/portraits/thumb/men/0.jpg",
    email: "vaino.honkala@example.com",
    favorite: false,
  },
  {
    name: "Ass. Stina Buvarp",
    gender: "female",
    group: "Assistant",
    email: "stina.buvarp@example.com",
    avatar: "https://randomuser.me/api/portraits/thumb/women/87.jpg",
    favorite: false,
  },
];
